 version: '3'
 
 services: 
   
   web: 
    image: israelfrank/work_tasks:webapp
    ports:
      - "80"
  
   db:
    image: mysql
    restart: always
    env_file:
     - env-file.env
    ports:
      - "3306:3306"
    volumes:
      - ./my-db:/var/lib/mysql
   
   nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8080:8080"