{{- define "common.configmap" -}}
{{- $common := dict "Values" .Values.common -}} 
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}apiVersion: v1
kind: ConfigMap
{{ template "common.metadata" . }}
data:
  url_mongo: {{ .Values.configmap.url }}
{{- end -}}
{{- end -}}
