{{- define "common.deployment" -}}
{{- $common := dict "Values" .Values.common -}} 
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}
apiVersion: apps/v1
kind: Deployment
{{ template "common.metadata" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "common.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: {{ .Values.service.targetPort }}
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
            valueFrom:
              secretKeyRef:
                name: {{ include "common.name" . }}
                key: username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
            valueFrom:
              secretKeyRef:
                name: {{ include "common.name" . }}
                key: password
          - name: ME_CONFIG_MONGODB_SERVER        
            valueFrom:
              configMapKeyRef:
                name: {{ include "common.name" . }}
                key: url_mongo  
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}
{{- end -}}