apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mongoex
  labels:
    app: mongoex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoex
  template:
    metadata:
      labels:
        app: mongoex
    spec:
      containers:
      - name: mongoex
        image: mongo-express:0.54.0
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
          valueFrom:
            secretKeyRef:
              name: secret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
        - name: ME_CONFIG_MONGODB_SERVER        
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: url_mongo 