apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-mongodb
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec: 
      containers:
      - name: mongo
        image: mongo:4.4.4
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: "/data/db"
            name: task-pv-storage
        env:
        - name: MONGO_INITDB_ROOT_USERNAME 
          valueFrom:
            secretKeyRef:
              name: secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: password

  volumeClaimTemplates:
  - metadata:
      name: task-pv-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi