apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.4
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME 
          value: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: pass
        #   - name: MONGO_INITDB_ROOT_USERNAME
        #     valueFrom:
        #       secretKeyRef:
        #         name: secret-mongodb
        #         key: username
        #   - name: MONGO_INITDB_ROOT_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: secret-mongodb
        #         key: password