apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: pvc    
      containers:
      - name: mongo
        image: mongo:4.4.4
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: "/data/db/"
            name: task-pv-storage
        env:
        - name: MONGO_INITDB_ROOT_USERNAME 
          valueFrom:
            secretKeyRef:
              name: secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: password