apiVersion: v1
kind: Service
metadata:
  name: service-mongoex
spec:
  selector:
    app: mongoex
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001